# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly Catalog generation - CI on PR

on:
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  build:
    name: ${{ matrix.os }}-jdk${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ['21']

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Validate catalog generation
        run: |
          version=$(cat version.txt)
          cd catalog-generator
          mvn clean install
          mvn exec:java -Dwildfly-version$version -DvalidateOnly=true
        shell: bash